server:
  port: 8081
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/terminus2?characterEncoding=UTF-8
        username: root
        password: 992050
        driver-class-name: com.mysql.jdbc.Driver

mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.hbrd.Dao
#  configuration:
#      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
